<a href="https://colab.research.google.com/github/mohaktiwari/MarvelTasks/blob/main/Metrics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Calculating Mean Squared Error(MSE)
from sklearn import metrics
y_real=[1,9,8,5,3]
y_pred=[2,9,7,6,3]
print(metrics.mean_squared_error(y_real,y_pred))

0.6


In [ ]:
#Calculating Root Mean Squared Error(RMSE)
import numpy as np
print(np.sqrt(metrics.mean_squared_error(y_real,y_pred)))

0.7745966692414834


In [ ]:
#Calculating R2 Score
print(metrics.r2_score(y_real,y_pred))

0.9330357142857143


In [ ]:
#Calculating Mean Absolute Error(MAE)
print(metrics.mean_absolute_error(y_real,y_pred))

0.6


In [ ]:
#Calculating Accuracy Score
print(metrics.accuracy_score(y_real,y_pred))

0.4


In [ ]:
#Plotting Confusion Matrix
y_real=[1,1,0,2,1]
y_pred=[1,0,0,2,1]
print(metrics.confusion_matrix(y_real,y_pred))

[[1 0 0]
 [1 2 0]
 [0 0 1]]


In [ ]:
#Calculating Precision Score
print(metrics.precision_score(y_real,y_pred,average='macro'))

0.8333333333333334


In [ ]:
#Calculating Recall Score
print(metrics.recall_score(y_real,y_pred,average='macro'))

0.8888888888888888


In [ ]:
#Calculating F1 Score
print(metrics.f1_score(y_real,y_pred,average='macro'))

0.8222222222222223
