<a href="https://colab.research.google.com/github/mohaktiwari/MarvelTasks/blob/main/NumPyOps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Creating an array by repeating values of small 1 dimensionional array
import numpy as np
arr1=np.array([1,2,3,4,5])
newarr1=np.repeat(arr1,3,axis=0)
print(newarr1)

[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]


In [ ]:
#Creating an array by repeating values of small 2 dimensionional array
arr2=np.array([[1,2],[3,4]])
newarr2=np.repeat(arr2,4,axis=1)
print(newarr2)

[[1 1 1 1 2 2 2 2]
 [3 3 3 3 4 4 4 4]]


In [ ]:
#Creating an array by repeating values of small 3 dimensionional array
arr3=np.array([[[1,2],[2,4]],[[5,6],[3,4]]])
newarr3=np.repeat(arr3,4,axis=2)
print(newarr3)

[[[1 1 1 1 2 2 2 2]
  [2 2 2 2 4 4 4 4]]

 [[5 5 5 5 6 6 6 6]
  [3 3 3 3 4 4 4 4]]]


In [ ]:
#Sorting the array using the index numbers
arr4=[4,3,8,1,6]
SortedArray=np.argsort(arr4)
print(SortedArray)

[3 1 0 4 2]
